# Generated by Django 5.0 on 2023-12-20 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('message_time',)},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Order status'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='gpt_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 12, 19, 0, 325260, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_message',
            field=models.TextField(blank=True),
        ),
    ]
